
export enum UserRole {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  COLLECTOR = 'COLLECTOR'
}

export enum CustomerStatus {
  ACTIVE = 'সক্রিয়',
  DUE = 'বকেয়া',
  DISCONNECTED = 'সংযোগ বিচ্ছিন্ন'
}

export enum ServiceType {
  INTERNET = 'ইন্টারনেট',
  DISH = 'ডিস',
  COMBO = 'কম্বো'
}

export enum RecurrenceInterval {
  MONTHLY = 'মাসিক',
  WEEKLY = 'সাপ্তাহিক'
}

export enum TicketStatus {
  OPEN = 'খোলা',
  ASSIGNED = 'অ্যাসাইনড',
  RESOLVED = 'সমাধানকৃত',
  CLOSED = 'বন্ধ'
}

export interface Package {
  id: string;
  name: string;
  speed: string;
  price: number;
  type: ServiceType;
}

export interface Customer {
  id: string;
  name: string;
  phone: string;
  address: string;
  packageId: string;
  serviceType: ServiceType;
  status: CustomerStatus;
  connectionDate: string;
  area: string;
  dueAmount: number;
  dueDate?: string;
  hardwareIssued?: string[]; // IDs of inventory items
}

export interface Payment {
  id: string;
  customerId: string;
  amount: number;
  date: string;
  method: 'নগদ' | 'বিকাশ' | 'নগদ (App)' | 'ব্যাংক';
  collectorId: string;
  discount?: number;
}

export interface Expense {
  id: string;
  category: string;
  amount: number;
  date: string;
  description: string;
  isAutoGenerated?: boolean;
}

export interface RecurringExpense {
  id: string;
  category: string;
  amount: number;
  description: string;
  interval: RecurrenceInterval;
  isActive: boolean;
  nextDueDate: string;
}

export interface Staff {
  id: string;
  name: string;
  role: UserRole;
  phone: string;
  area: string;
  salary: number;
}

export interface InventoryItem {
  id: string;
  name: string;
  category: 'Router' | 'ONU' | 'Cable' | 'Splitter' | 'Other';
  stock: number;
  unitPrice: number;
  supplier?: string;
}

export interface SupportTicket {
  id: string;
  customerId: string;
  subject: string;
  description: string;
  status: TicketStatus;
  priority: 'Low' | 'Medium' | 'High';
  assignedStaffId?: string;
  createdAt: string;
  resolvedAt?: string;
}
